### ISSUE TITLE
Art: "Basic" patrons

### ISSUE THREAD

**Issue by saporter** [FortWorthGameDev/MayByMoonlight#12]
Pick an animal to represent our basic patron and deliver some 3D art assets for that character

https://docs.google.com/document/d/1YmSmHOAYKzmCU9hBz_QsyhOy-GWBxBwKasGI5-ZyYhw/edit#bookmark=id.kh8wyr29fx3q

Construction of patron prefabs:
https://docs.google.com/document/d/1YmSmHOAYKzmCU9hBz_QsyhOy-GWBxBwKasGI5-ZyYhw/edit#bookmark=id.v9mltl21hhfp

**Comment by LanceBailey** [comment]
Refer to the GDD section 5.2, or refer to the "Sphere Patron" prefab, for more information on creating new patrons in Unity.

**Comment by LanceBailey** [comment]
Bumping this up to "Feature" level, as having visually distinct patrons is important to gameplay.  It might be better to break it down into 9 different animals soon, so that people have a bit more direction.
