### ISSUE TITLE
Patrons cause a penalty if not served

### ISSUE THREAD

**Issue by LanceBailey** [FortWorthGameDev/MayByMoonlight#44]
Required for #45

Reference:
https://docs.google.com/document/d/1YmSmHOAYKzmCU9hBz_QsyhOy-GWBxBwKasGI5-ZyYhw/edit#bookmark=id.jevttwg4u16d

Patrons currently just keep walking away forever.   There should be a penalty to your bucks if a patron reaches the end of the bar.

**Comment by ciscom1971** [comment]
adding collider at end of bar to destroy drinks
