### ISSUE TITLE
framerate issue with multi-camera rendertexture

### ISSUE THREAD

**Issue by saporter** [FortWorthGameDev/MayByMoonlight#59]

**Comment by LanceBailey** [comment]
Bad news, this doesn't seem to be a bug with multiple cameras rendering.  Leaving the issue open.  Unfortunately, rendering the scene at all seems to be the problem (even after fiddling with lighting settings).

**Comment by saporter** [comment]
Interesting.  How can I duplicate this problem?  I don't see it

**Comment by saporter** [comment]
Closing this out.  Let me know if this actually an issue.
