### ISSUE TITLE
Drinks and Patrons move automatically down lanes

### ISSUE THREAD

**Issue by saporter** [FortWorthGameDev/MayByMoonlight#6]
Given a Drink or Patron game object and a chosen lane (see #4 and #5), Drinks and Patrons move along chosen lanes.

Patrons and Drinks should detect collisions with one another and raise a Scoring event.  This "Scoring event" can be a Log message for now.

**Comment by LanceBailey** [comment]
The patron spawner script looks for a Patron script, the spawner currently needs the Patron to have a "seenEverySeconds" that is their spawn rate.  This should probably be done better, as it is right now it can be swingy (sometimes way too many, sometimes too few).

**Comment by saporter** [comment]
@Zaneeverett @LanceBailey Is this done?  Drinks spawn and those look like patrons??

**Comment by LanceBailey** [comment]
Minor tweak to make patrons collect drinks, #26.  Closing #6
