### ISSUE TITLE
Patron spawner

### ISSUE THREAD

**Issue by saporter** [FortWorthGameDev/MayByMoonlight#7]
Patrons should be spawned randomly on a chosen lane.  

A patron should have a drink preference for:
Alcohol - Whiskey, Rum, Vodka
Mixer - Soda, Coke or Vermouth 
Garnish - Cherry, Lime or Olive

See #4 and #5 for different ways a drink might be mixed.  We'll playtest and decide later on a drink convention

**Comment by LanceBailey** [comment]
Rough patron spawner working, and two mock patrons (sphere, cylinder) that just slide left.

Will be enhanced when various patrons are created.  Currently no drink preferences for prototype patrons.
